Only first input file is now used

diff --git a/results b/results
--- a/results
+++ b/results
@@ -112,47 +112,45 @@ function normalizeFileWithSpaces(){
 }
 
 function parseInputFiles(){
-    for (( j=0; j<argc; j++ )); do
-        file=${argv[j]}
-        
-        if !( [ -f "$file" ] && [ -s "$file" ] ) ; then
-            result="${result}${RED_COLOR}Error, file \"$file\" is missing or empty${COLOR_OFF}\n"
-        fi
+    file=${argv[0]}
+    
+    if !( [ -f "$file" ] && [ -s "$file" ] ) ; then
+        result="${result}${RED_COLOR}Error, file \"$file\" is missing or empty${COLOR_OFF}\n"
+    fi
 
-        if [ -f "$file" ] && [ -s "$file" ] ; then
-            tmpFile=tmp.txt
-            cp $file $tmpFile
+    if [ -f "$file" ] && [ -s "$file" ] ; then
+        tmpFile=tmp.txt
+        cp $file $tmpFile
 
-            if ! [ -z "$(grep -Ev "$LINE_REGEXP" $tmpFile)" ] && ! [ -z "$(grep -Ev "$LINE_REGEXP_W_SPACES" $tmpFile)" ]; then
+        if ! [ -z "$(grep -Ev "$LINE_REGEXP" $tmpFile)" ] && ! [ -z "$(grep -Ev "$LINE_REGEXP_W_SPACES" $tmpFile)" ]; then
+            firstInvalidLine=$(grep -Evn "$LINE_REGEXP" $tmpFile | head -n 1)
+            lineNumber=$(echo $firstInvalidLine | cut -f 1 -d ':')
+            firstInvalidLine=$(grep -Ev "$LINE_REGEXP" $tmpFile | head -n 1)
+            result="${result}${RED_COLOR}Error in \"$file\", invalid line $lineNumber: \"$firstInvalidLine\"\n\tvalid line \"Team1-Team2:Goals1-Goals2\" should be matched by LINE_REGEXP=\"$LINE_REGEXP\" ${COLOR_OFF}\n"
+        else
+            if ! [ -z "$(grep -Ev "$LINE_REGEXP" $tmpFile)" ]; then
                 firstInvalidLine=$(grep -Evn "$LINE_REGEXP" $tmpFile | head -n 1)
                 lineNumber=$(echo $firstInvalidLine | cut -f 1 -d ':')
                 firstInvalidLine=$(grep -Ev "$LINE_REGEXP" $tmpFile | head -n 1)
-                result="${result}${RED_COLOR}Error in \"$file\", invalid line $lineNumber: \"$firstInvalidLine\"\n\tvalid line \"Team1-Team2:Goals1-Goals2\" should be matched by LINE_REGEXP=\"$LINE_REGEXP\" ${COLOR_OFF}\n"
+                printf "${YELLOW_COLOR}Error in \"$file\", spaces in team at line $lineNumber: \"$firstInvalidLine\"\n\tTrying to continue with spaces...${COLOR_OFF}\n"
+                normalizeFileWithSpaces
+                table="table.csv"
+                initializeStandings
+                calculateStandings
+                counter=1
+                result="$(sed 's/,/ /g' $table | sort -k2,2nr -k1,1 | tr ' ' '\t' | tr '_' ' ' | while read i; do printf "$counter.\t$i\n"; counter=$((counter+1)); done)\n"
             else
-                if ! [ -z "$(grep -Ev "$LINE_REGEXP" $tmpFile)" ]; then
-                    firstInvalidLine=$(grep -Evn "$LINE_REGEXP" $tmpFile | head -n 1)
-                    lineNumber=$(echo $firstInvalidLine | cut -f 1 -d ':')
-                    firstInvalidLine=$(grep -Ev "$LINE_REGEXP" $tmpFile | head -n 1)
-                    printf "${YELLOW_COLOR}Error in \"$file\", spaces in team at line $lineNumber: \"$firstInvalidLine\"\n\tTrying to continue with spaces...${COLOR_OFF}\n"
-                    normalizeFileWithSpaces
-                    table="table.csv"
-                    initializeStandings
-                    calculateStandings
-                    counter=1
-                    result="$(sed 's/,/ /g' $table | sort -k2,2nr -k1,1 | tr ' ' '\t' | tr '_' ' ' | while read i; do printf "$counter.\t$i\n"; counter=$((counter+1)); done)\n"
-                else
-                    normalizeFile
-                    table="table.csv"
-                    initializeStandings
-                    calculateStandings
-                    counter=1
-                    result="$(sed 's/,/ /g' $table | sort -k2,2nr -k1,1 | tr ' ' '\t' | while read i; do printf "$counter.\t$i\n"; counter=$((counter+1)); done)\n"
-                fi
-                rm $table
+                normalizeFile
+                table="table.csv"
+                initializeStandings
+                calculateStandings
+                counter=1
+                result="$(sed 's/,/ /g' $table | sort -k2,2nr -k1,1 | tr ' ' '\t' | while read i; do printf "$counter.\t$i\n"; counter=$((counter+1)); done)\n"
             fi
-            rm $tmpFile
+            rm $table
         fi
-    done
+        rm $tmpFile
+    fi
 }
 
 function printResult(){
